name: Collection of my links
url: https://teaeg.github.io
markdown: kramdown
#
defaults:
#   default for pages/posts: layout and permalink ---------
  -
    scope:
      path: ""
    values:
      layout: plain
